### ISSUE TITLE
yStrikeoutPosition="0"

### ISSUE THREAD

**Issue by thlinard** [Omnibus-Type/Asap#5]
[Issue #2436 on Google Fonts](https://github.com/google/fonts/issues/2436).

**Comment by Omnibus-Type** [comment]
Hi @thlinard recently we recently added an update where we removed a custom parameter that was complicating everything with strikethrough, hope it works properly.

**Comment by thlinard** [comment]
Hi @Omnibus-Type sounds good! I look forward to the release of this new version!
