### ISSUE TITLE
Weight Axis variable font

### ISSUE THREAD

**Issue by pichotta** [Omnibus-Type/Asap#6]
@Yorlmar 
@Omnibus-Type 
@davelab6

Hello Pablo and Omnibus,

The Google fonts team would love to see a variable font version of ‘**Asap**'. They have commissioned us @TypeNetwork to work on upgrading a number of font projects to be variable fonts with a single weight axis.

In order to achieve the highest quality and most efficient long term results we will be converting the source data from Glyphs to UFO. The new source data will be generated in the RoboFont environment using fontmake and ttfautohint. There has been progress on tools to make an easy path to move between the Glyphs and Robofont environment.

During the process we will be looking to improve any errors while preserving how the font appears and renders on different platforms.

We have started by making a fork off of this git repository. The upgrade will be completed for you in the near future. When the proposed final font is approved by Google they will accept a pull request.

Does this repository have the most current font data for '**Asap**'?

We hope this answers some of your questions about the process. Please let us know if you have any additional comments.

Best Regards,

Jill Pichotta
Vice President
Type Network
pichotta@typenetwork.com

**Comment by Yorlmar** [comment]
Hi @pichotta the correct files belong to the following directory [(https://github.com/Omnibus-Type/Asap)], the other directory was created thinking about how to solve the structure of the whole family, but it was outdated, so we are going to eliminate it to avoid confusion. Thanks for the advice!
